# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameserverapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='players', to='gameserverapp.Player'),
        ),
    ]
