# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 05:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameserverapp', '0002_auto_20160904_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), size=None), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('w', 'Waiting to start'), ('s', 'Started'), ('f', 'Finished')], max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='scores',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='words_done',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
    ]
