# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameserverapp', '0003_auto_20160905_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_player', to='gameserverapp.Player'),
        ),
    ]
