# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameserverapp', '0005_auto_20160905_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
