# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameserverapp', '0007_player_local_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pass_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
