# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameserverapp', '0008_game_pass_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='local_score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_id',
        ),
        migrations.AlterField(
            model_name='player',
            name='nick',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
