# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameserverapp', '0009_auto_20160908_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('w', 'Waiting for start'), ('s', 'Started'), ('f', 'Finished')], max_length=1),
        ),
    ]
