# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameserverapp', '0010_auto_20160909_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_cols',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='game',
            name='board_rows',
            field=models.IntegerField(default=15),
        ),
    ]
