# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 08:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameserverapp', '0012_auto_20160910_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='turn_seq',
        ),
        migrations.AddField(
            model_name='game',
            name='num_words',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='game',
            name='words_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='words_done',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
