# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 09:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameserverapp', '0013_auto_20160910_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn_sequence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
            preserve_default=False,
        ),
    ]
