# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 09:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameserverapp', '0015_auto_20160910_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_status', models.CharField(choices=[('w', 'Waiting for start'), ('s', 'Started'), ('f', 'Finished')], max_length=1)),
                ('turn_sequence', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('words_done', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField()),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('pass_count', models.IntegerField()),
                ('admin_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_player', to='gameserverapp.Player')),
                ('current_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_player', to='gameserverapp.Player')),
                ('players', models.ManyToManyField(related_name='player', to='gameserverapp.Player')),
            ],
        ),
    ]
