# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 12:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameserverapp', '0017_game_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='placed_words',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
